name: github_intelligence
version: "1.0.0"
profile: github_intelligence
model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"

models:
  github_intelligence:
    staging:
      +materialized: view
    enrichment:
      +materialized: table
    marts:
      +materialized: table
