telemetry:
  enabled: false
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 1
run_monitoring:
  enabled: true
  max_runtime_seconds: 1500
