apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub
  namespace: prefect
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - HUB_DOMAIN_PLACEHOLDER
      secretName: hub-tls
  rules:
    - host: HUB_DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hub
                port:
                  number: 3000
