server:
  replicaCount: 1

  basicAuth:
    enabled: true
    existingSecret: prefect-auth

  uiConfig:
    prefectUiApiUrl: "https://DOMAIN_PLACEHOLDER/api"

  env:
    - name: PREFECT_SERVER_UI_SHOW_PROMOTIONAL_CONTENT
      value: "false"
    - name: PREFECT_SERVER_UI_V2_ENABLED
      value: "true"

  extraEnvVarsCM: prefect-docket-config

backgroundServices:
  runAsSeparateDeployment: true
  replicaCount: 1
  extraEnvVarsCM: prefect-docket-config

postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    database: prefect
    username: prefect
  primary:
    persistence:
      enabled: true
      size: 10Gi

redis:
  enabled: true
  architecture: standalone

ingress:
  enabled: true
  className: traefik
  host:
    hostname: DOMAIN_PLACEHOLDER
    path: /
    pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true
