<script lang="ts">
    import { duration, isWorking, needsAttention, workTitle, type Gardener } from '$lib/gardener';
    let { model, now, formatDate }: { model: Gardener; now: number; formatDate: (value: string) => string } = $props();
    let inspected = $state<'queue' | 'worker' | 'inference' | 'machines' | null>(null);
    let observed = $derived(model.snapshot?.observed_at);
    let fresh = $derived(observed !== null && observed !== undefined && now - observed * 1000 < 90_000 && !model.snapshot?.observer_error);
    let online = $derived(model.workers.filter(worker => worker.status === 'ONLINE' && worker.last_heartbeat_time && now - Date.parse(worker.last_heartbeat_time) < 90_000));
    let hostWorkers = $derived(model.workers.filter(worker => worker.name === model.snapshot?.worker));
    let otherWorkers = $derived(model.workers.filter(worker => worker.name !== model.snapshot?.worker));
    let attempts = $derived(model.snapshot?.attempts ?? []);
    let machines = $derived(attempts.filter(attempt => !['deleted', 'missing'].includes(attempt.phase)));
    let queued = $derived(model.runs.filter(run => ['SCHEDULED', 'PENDING'].includes(run.state_type ?? '') && !run.infrastructure_pid));
    let working = $derived(model.runs.filter(isWorking));
    let finished = $derived(model.runs.filter(run => run.state_type === 'COMPLETED'));
    let attention = $derived(model.runs.filter(run => needsAttention(run, attempts.find(attempt => attempt.vm === run.infrastructure_pid))));
    let unobserved = $derived(working.filter(run => !machines.some(attempt => attempt.flow_run_id === run.id) && !queued.includes(run)));
    const workUrl = (id: string) => `?view=work&run=${id}`;
</script>

<section class="overview" aria-label="Gardener system map">
    <div class="overview-heading"><div><h1>Where the work is</h1><p>{fresh ? 'Current worker observations' : 'Last known worker observations'} · gardener-exe</p></div><span class="observation" class:delayed={!fresh}><span class="dot"></span>{fresh ? 'Up to date' : 'Observations delayed'}</span></div>
    <div class="census" aria-label="System counts">
        <button onclick={() => inspected = 'worker'}><strong>{online.length}</strong><span>worker{online.length === 1 ? '' : 's'} online</span></button>
        <button onclick={() => inspected = 'machines'}><strong>{model.snapshot ? model.snapshot.active_attempts : '—'}</strong><span>machine{model.snapshot?.active_attempts === 1 ? '' : 's'}{fresh ? '' : ' · last known'}</span></button>
        <a href="?view=work&filter=working"><strong>{working.length}</strong><span>job{working.length === 1 ? '' : 's'} in progress</span></a>
        <a href="?view=work&filter=attention" class:alert={attention.length > 0}><strong>{attention.length}</strong><span>needs attention</span></a>
    </div>

    <div class="map" aria-label="Queue to worker to exe.dev machines to results">
        <section class="control-zone" aria-label="Control and dispatch">
            <div class="zone-label"><h2>Control & dispatch</h2><span>Persistent services</span></div>
            <div class="queue-area"><button class="queue node" class:chosen={inspected === 'queue'} onclick={() => inspected = inspected === 'queue' ? null : 'queue'}>
                <div class="node-top"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="7" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="10" cy="18" r="2"/></svg><strong>Prefect</strong><span class="node-count">{queued.length}</span></div>
                <div class="node-caption"><span>{model.pool.is_paused ? 'Queue paused' : 'Queued requests'}</span><span>Hetzner</span></div>
                <div class="workflow-count">{model.deployments.length} workflows</div><div class="workflow-chips">{#each model.deployments as deployment}<span>{deployment.name}</span>{/each}</div>
            </button>
            {#each queued as run}<a class="queued-work" href={workUrl(run.id)}>{workTitle(run)}</a>{/each}</div>
            <div class="vertical-wire" aria-hidden="true"><span>polls for work</span><span>↓</span></div>
            <div class="host"><h3>{model.snapshot?.host ?? 'Worker host unreported'}</h3>
                {#each hostWorkers as worker}
                    {@const isOnline = online.includes(worker)}
                    <button class="worker node" class:chosen={inspected === 'worker'} onclick={() => inspected = inspected === 'worker' ? null : 'worker'}><div class="node-top"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="6" rx="1"/><rect x="3" y="14" width="18" height="6" rx="1"/><path d="M7 7h1M7 17h1"/></svg><strong>exe worker</strong><span class="dot" class:offline={!isOnline}></span></div><p>{isOnline ? 'Online' : 'Heartbeat overdue'} · {worker.name}</p></button>
                {:else}<p class="host-empty">No worker registered</p>{/each}
                <button class="gateway" class:chosen={inspected === 'inference'} onclick={() => inspected = inspected === 'inference' ? null : 'inference'}><span class="gateway-symbol" aria-hidden="true">⇄</span><div><strong>Inference gateway</strong><span>Scoped model access for Pi</span></div></button>
            </div>
        </section>
        <div class="wire dispatch-wire" aria-hidden="true"><span>creates</span><svg viewBox="0 0 60 24"><path d="M0 12h54m-8-7 8 7-8 7"/></svg><small>one VM<br/>per attempt</small></div>
        <section class="execution-zone" aria-label="exe.dev machines">
            <div class="zone-label"><h2>exe.dev</h2><span>Execution</span></div>
            <div class="cloud" class:idle={machines.length === 0}>
                <div class="cloud-heading"><strong>{model.snapshot ? model.snapshot.active_attempts : '—'}</strong><div><h3>Machines</h3><span>{fresh ? 'Active or retained' : 'Last known count'}</span></div></div>
                {#if machines.length}
                    <div class="machines">{#each machines as machine}
                        {@const run = model.runs.find(run => run.id === machine.flow_run_id)}
                        <a href={run ? workUrl(run.id) : `https://prefect-server.waow.tech/runs/flow-run/${machine.flow_run_id}`} class="machine" class:retained={machine.phase === 'retained'}><div class="machine-top"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="16" height="12" rx="2"/><path d="M8 20h8m-4-4v4"/></svg><span>{machine.phase}</span></div><strong>{run ? workTitle(run) : machine.run_name ?? 'Execution attempt'}</strong><span>{machine.error ?? 'Pi in an isolated workspace'}</span></a>
                    {/each}</div>
                    {#if (model.snapshot?.active_attempts ?? 0) > machines.length}<p class="inventory-note">Showing {machines.length} of {model.snapshot?.active_attempts} recorded machines.</p>{/if}
                {:else}
                    <button class="idle-machine" onclick={() => inspected = 'machines'}><svg viewBox="0 0 100 82" aria-hidden="true"><rect x="14" y="10" width="72" height="48" rx="7"/><path d="M35 73h30M50 58v15M37 32h26"/></svg><strong>{fresh ? 'No machines running' : 'No machines in the last report'}</strong><span>{fresh ? 'A new request creates a fresh VM here.' : 'A fresh worker report is needed to confirm this.'}</span></button>
                {/if}
                {#each unobserved as run}<a class="unobserved" href={workUrl(run.id)}><strong>{workTitle(run)}</strong><span>In progress · waiting for machine observations</span></a>{/each}
                <div class="cloud-footer"><span class="small-dot"></span>Pi runs here · inference routes back to heavypad</div>
            </div>
            <div class="lifecycle"><span>Create</span><span>→</span><span>Run</span><span>→</span><span>Save</span><span>→</span><span>Delete</span></div>
        </section>
        <div class="wire results-wire" aria-hidden="true"><span>saves</span><svg viewBox="0 0 60 24"><path d="M0 12h54m-8-7 8 7-8 7"/></svg><small>results &<br/>diagnostics</small></div>
        <section class="outcomes-zone" aria-label="Recent outcomes">
            <div class="zone-label"><h2>Recent work</h2><span>{model.runs.length} requests loaded</span></div>
            <div class="outcome-group attention"><a class="group-heading" href="?view=work&filter=attention"><span class="group-icon" aria-hidden="true">!</span><h3>Needs attention</h3><strong>{attention.length}</strong></a>
                {#each attention.slice(0, 3) as run}<a class="work-token" href={workUrl(run.id)}><span class="token-dot"></span><span>{workTitle(run)}</span><span aria-hidden="true">›</span></a>{:else}<p class="quiet-state">Nothing needs review.</p>{/each}
                {#if attention.length > 3}<a class="more" href="?view=work&filter=attention">View all {attention.length}</a>{/if}
            </div>
            <div class="outcome-group finished"><a class="group-heading" href="?view=work&filter=finished"><span class="group-icon" aria-hidden="true">✓</span><h3>Finished</h3><strong>{finished.length}</strong></a>
                {#each finished.slice(0, 4) as run}<a class="work-token" href={workUrl(run.id)}><span class="token-dot"></span><span>{workTitle(run)}</span><span aria-hidden="true">›</span></a>{:else}<p class="quiet-state">Results will appear here.</p>{/each}
                {#if finished.length > 4}<a class="more" href="?view=work&filter=finished">View all {finished.length}</a>{/if}
            </div>
        </section>
    </div>

    {#if inspected}
        <aside class="inspector" aria-label="Selected system component"><button class="close" onclick={() => inspected = null} aria-label="Close component details">×</button>
            {#if inspected === 'queue'}<h2>Prefect owns the queue</h2><p>{model.pool.is_paused ? 'The pool is paused.' : 'The pool is accepting work.'} {queued.length} requests are waiting for a machine. {model.pool.concurrency_limit ? `Up to ${model.pool.concurrency_limit} runs can execute at once.` : 'No pool concurrency limit is configured.'}</p><div class="detail-links">{#each model.deployments as item}<a href={`https://prefect-server.waow.tech/deployments/deployment/${item.id}`} target="_blank" rel="noreferrer">{item.name} · {duration(item.job_variables.timeout_seconds ?? null)} limit ↗</a>{/each}</div>
            {:else if inspected === 'worker'}<h2>{online.length} worker{online.length === 1 ? '' : 's'} online</h2><p>The worker polls Prefect, creates a VM for each attempt, and reconciles its outcome and cleanup. Closing this page does not affect it.</p><p class="detail-meta">Last machine check: {observed ? formatDate(new Date(observed * 1000).toISOString()) : 'Not recorded'}</p>
            {:else if inspected === 'inference'}<h2>Model access goes through heavypad</h2><p>Each attempt receives a grant restricted to one model, with an expiry and a 32-request limit. The grant is revoked when execution ends. This map shows the configured route; it does not independently probe gateway health.</p>
            {:else}<h2>{model.snapshot ? model.snapshot.active_attempts : 'Unknown number of'} machines active or retained</h2><p>{fresh ? 'The latest worker report is current.' : 'These observations are delayed or unavailable.'} Each attempt gets its own exe.dev VM. The worker saves diagnostics and deletes the machine after execution.</p><p class="detail-meta">{model.deployments.some(item => item.job_variables.image) ? 'Images are configured per deployment.' : 'Current deployments use the default exe.dev image and install dependencies at startup.'}</p>{/if}
        </aside>
    {/if}
    <footer class="map-footer">{#if otherWorkers.length}<details class="other-workers"><summary>{otherWorkers.length} other worker registration{otherWorkers.length === 1 ? '' : 's'}</summary>{#each otherWorkers as worker}<p>{worker.name}: {online.includes(worker) ? 'online, host unreported' : 'no recent heartbeat; host unreported'}</p>{/each}</details>{/if}<p>Select a worker, machine, or request to inspect it. Machine counts cover this pool; outcomes cover the {model.runs.length} loaded requests.</p><div><a href="https://prefect-metrics.waow.tech/d/executive-overview/executive-overview" target="_blank" rel="noreferrer">Grafana · infrastructure ↗</a><a href="https://agents.zzstoatzz.io" target="_blank" rel="noreferrer">Agents · conversations ↗</a></div></footer>
</section>

<style>
    .overview { max-width: 1460px; padding: 30px 28px 40px; margin: 0 auto; }
    .overview-heading { display: flex; align-items: center; justify-content: space-between; gap: 20px; } h1 { font-size: 30px; line-height: 1.25; font-weight: 650; letter-spacing: -.025em; } .overview-heading p { margin-top: 8px; font-size: 15px; color: var(--muted); }
    .observation { display: flex; align-items: center; gap: 9px; font-size: 15px; color: var(--green); } .dot { display: inline-block; width: 10px; height: 10px; background: var(--green); border-radius: 50%; flex-shrink: 0; } .delayed, .offline { color: var(--red); } .delayed .dot, .dot.offline { background: var(--red); }
    .census { display: flex; gap: 32px; margin: 28px 0 36px; flex-wrap: wrap; } .census > * { display: flex; align-items: baseline; gap: 10px; text-align: left; min-height: 44px; } .census strong { font-size: 34px; line-height: 1; letter-spacing: -.045em; font-weight: 650; } .census span { color: var(--muted); font-size: 16px; } .census .alert strong { color: var(--red); }
    .map { display: grid; grid-template-columns: minmax(240px,1fr) 56px minmax(270px,1.12fr) 56px minmax(250px,1fr); align-items: start; background-image: radial-gradient(var(--line) .7px, transparent .7px); background-size: 18px 18px; border-radius: 16px; padding: 20px 0; }
    .zone-label { display: flex; align-items: center; gap: 12px; flex-wrap: wrap; margin-bottom: 18px; } .zone-label h2 { font-size: 20px; font-weight: 650; } .zone-label > span { color: var(--muted); font-size: 13px; background: var(--canvas); }
    .queued-work { display: block; padding: 14px; margin-top: 10px; background: var(--surface); border-left: 3px solid var(--blue); border-radius: 6px; font-size: 15px; line-height: 1.5; }
    .node { display: block; text-align: left; width: 100%; padding: 20px; border: 1px solid var(--line); border-radius: 12px; background: var(--surface); box-shadow: 0 3px 0 var(--line); } .node:hover, .gateway:hover, .idle-machine:hover { border-color: var(--blue); } .chosen { outline: 2px solid var(--blue); outline-offset: 2px; }
    svg { fill: none; stroke: currentColor; stroke-width: 1.6; stroke-linecap: round; stroke-linejoin: round; } .node-top { display: flex; align-items: center; gap: 12px; } .node-top svg { width: 25px; height: 25px; color: var(--blue); } .node-top strong { font-size: 20px; font-weight: 650; } .node-count { margin-left: auto; font-size: 27px; font-weight: 600; } .node-caption { display: flex; justify-content: space-between; gap: 8px; margin-top: 12px; color: var(--muted); font-size: 14px; }
    .workflow-count { font-size: 13px; color: var(--muted); margin-top: 16px; } .workflow-chips { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 8px; } .workflow-chips span { font-size: 12px; border: 1px solid var(--line); padding: 4px 7px; border-radius: 5px; color: var(--muted); }
    .vertical-wire { display: flex; align-items: center; flex-direction: column; gap: 4px; height: 57px; padding-top: 10px; color: var(--muted); font-size: 12px; } .vertical-wire span:last-child { font-size: 22px; line-height: 1; }
    .host { background: var(--wash); border: 1px solid var(--line); border-radius: 15px; padding: 16px; } .host h3 { font-size: 16px; font-weight: 600; margin-bottom: 14px; } .worker { padding: 16px; } .worker .dot { margin-left: auto; } .worker p { font-size: 12px; color: var(--muted); margin-top: 12px; overflow-wrap: anywhere; } .worker + .worker { margin-top: 12px; }
    .gateway { display: flex; gap: 12px; align-items: center; text-align: left; width: 100%; border: 1px dashed var(--line); border-radius: 10px; padding: 16px 8px 8px; margin-top: 18px; } .gateway-symbol { font-size: 26px; color: var(--blue); } .gateway strong { display: block; font-size: 15px; } .gateway div > span { display: block; font-size: 12px; margin-top: 4px; color: var(--muted); }
    .wire { text-align: center; color: var(--blue); margin-top: 230px; } .wire > span { font-size: 12px; background: var(--canvas); } .wire svg { width: 100%; height: 24px; stroke-width: 2; } .wire small { display: block; font-size: 11px; line-height: 1.5; color: var(--muted); background: var(--canvas); }
    .cloud { background: var(--selection); border: 2px solid var(--blue); border-radius: 22px; min-height: 445px; padding: 24px; display: flex; flex-direction: column; } .cloud.idle { border-style: dashed; }
    .cloud-heading { display: flex; align-items: center; gap: 14px; } .cloud-heading > strong { font-size: 46px; line-height: 1; font-weight: 650; letter-spacing: -.04em; color: var(--blue); } .cloud-heading h3 { font-size: 22px; font-weight: 600; } .cloud-heading span { color: var(--muted); font-size: 14px; }
    .idle-machine { display: flex; flex-direction: column; align-items: center; flex: 1; justify-content: center; text-align: center; margin: 20px 0; padding: 12px 0; } .idle-machine svg { width: 92px; height: 76px; color: var(--blue); margin-bottom: 20px; stroke-width: 2; } .idle-machine strong { font-size: 19px; font-weight: 600; } .idle-machine > span { color: var(--muted); font-size: 15px; line-height: 1.6; margin-top: 10px; max-width: 230px; }
    .cloud-footer { border-top: 1px solid var(--line); padding-top: 16px; color: var(--muted); font-size: 13px; line-height: 1.6; } .small-dot { display: inline-block; width: 7px; height: 7px; border-radius: 50%; background: var(--blue); margin-right: 4px; } .lifecycle { display: flex; gap: 10px; justify-content: center; margin-top: 16px; color: var(--muted); font-size: 13px; }
    .machines { display: grid; gap: 12px; margin: 22px 0; } .machine { display: block; background: var(--surface); border: 1px solid var(--blue); border-radius: 10px; padding: 16px; } .machine-top { display: flex; gap: 12px; align-items: center; color: var(--blue); margin-bottom: 12px; font-size: 14px; } .machine-top svg { width: 28px; height: 28px; } .machine > strong { font-size: 16px; line-height: 1.5; display: block; } .machine > span { display: block; color: var(--muted); font-size: 13px; margin-top: 8px; } .machine.retained { border-color: var(--red); } .unobserved { display: block; padding: 14px 0; } .unobserved span { display: block; color: var(--muted); margin-top: 8px; font-size: 14px; }
    .outcome-group { background: var(--surface); border: 1px solid var(--line); border-radius: 12px; overflow: hidden; margin-bottom: 18px; } .group-heading { display: flex; align-items: center; gap: 10px; padding: 16px; background: var(--green-wash); color: var(--green); } .group-heading h3 { font-size: 17px; font-weight: 600; } .group-heading > strong { margin-left: auto; font-size: 25px; font-weight: 650; } .group-icon { border: 1.5px solid currentColor; border-radius: 50%; width: 22px; height: 22px; display: grid; place-items: center; font-size: 14px; font-weight: 600; } .attention .group-heading { background: var(--red-wash); color: var(--red); }
    .work-token { display: flex; gap: 10px; align-items: baseline; padding: 16px; border-top: 1px solid var(--line); font-size: 15px; line-height: 1.5; } .work-token:hover { background: var(--wash); } .work-token > span:last-child { margin-left: auto; color: var(--muted); font-size: 22px; } .token-dot { flex-shrink: 0; width: 8px; height: 8px; background: var(--green); border-radius: 50%; } .attention .token-dot { background: var(--red); } .quiet-state { padding: 16px; color: var(--muted); font-size: 15px; } .more { display: block; padding: 14px 16px; color: var(--blue); font-size: 14px; }
    .inspector { position: fixed; z-index: 10; bottom: 24px; right: 24px; width: min(480px, calc(100vw - 32px)); max-height: 65vh; overflow-y: auto; box-shadow: 0 12px 48px #14253630; background: var(--surface); border: 2px solid var(--blue); border-radius: 12px; padding: 26px 58px 26px 26px; max-width: 1000px; } .inspector h2 { font-size: 23px; font-weight: 650; margin-bottom: 12px; } .inspector p { max-width: 800px; line-height: 1.7; } .close { position: absolute; right: 10px; top: 10px; font-size: 30px; width: 44px; height: 44px; } .detail-meta { margin-top: 12px; color: var(--muted); font-size: 15px; } .detail-links { display: flex; gap: 20px; flex-wrap: wrap; margin-top: 16px; } .detail-links a { color: var(--blue); font-size: 15px; text-decoration: underline; }
    .map-footer { margin-top: 28px; padding-top: 20px; border-top: 1px solid var(--line); color: var(--muted); font-size: 14px; line-height: 1.6; } .other-workers { margin-bottom: 16px; } .other-workers summary { cursor: pointer; padding: 8px 0; } .map-footer > div { display: flex; flex-wrap: wrap; gap: 24px; margin-top: 12px; } .map-footer a { color: var(--blue); text-decoration: underline; text-underline-offset: 3px; }
    @media (max-width: 1050px) and (min-width: 761px) { .map { grid-template-columns: minmax(220px,1fr) 42px minmax(260px,1.1fr); } .results-wire { display: none; } .outcomes-zone { grid-column: 1 / -1; margin-top: 28px; display: grid; grid-template-columns: 1fr 1fr; gap: 16px; } .outcomes-zone .zone-label { grid-column: 1 / -1; margin-bottom: 0; } }
    @media (max-width: 760px) { .overview { padding: 24px 18px; } h1 { font-size: 26px; } .overview-heading { align-items: start; } .overview-heading p { font-size: 13px; max-width: 220px; line-height: 1.5; } .observation { font-size: 12px; white-space: nowrap; margin-top: 8px; } .observation .dot { width: 7px; height: 7px; } .census { display: grid; grid-template-columns: 1fr 1fr; gap: 20px 16px; margin: 26px 0; } .census strong { font-size: 32px; } .census span { font-size: 14px; } .map { display: flex; flex-direction: column; padding: 0; gap: 0; } .map > section { width: 100%; } .zone-label { margin-bottom: 14px; } .control-zone { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; } .control-zone .zone-label { grid-column: 1 / -1; margin: 0; } .queue-area { align-self: stretch; } .queue { padding: 14px; min-height: 100%; } .queue .node-top { flex-wrap: wrap; gap: 8px; } .queue .node-top strong { font-size: 18px; } .queue .node-top svg { width: 20px; } .node-count { font-size: 24px; } .node-caption { flex-direction: column; font-size: 12px; } .workflow-chips { gap: 5px; } .workflow-chips span { font-size: 11px; overflow-wrap: anywhere; max-width: 100%; } .vertical-wire { display: none; } .host { padding: 12px; } .host h3 { font-size: 14px; margin-bottom: 10px; } .worker { padding: 12px; box-shadow: none; } .worker .node-top { flex-wrap: wrap; gap: 6px; } .worker .node-top svg { width: 20px; } .worker .node-top strong { font-size: 15px; } .worker p { font-size: 12px; line-height: 1.5; } .gateway { padding: 8px 0; gap: 6px; margin-top: 12px; } .gateway strong { font-size: 12px; } .gateway div > span { display: none; } .gateway-symbol { font-size: 22px; } .wire { display: flex; align-items: center; justify-content: center; gap: 12px; margin: 12px 0; width: 100%; height: 28px; } .wire svg { width: 32px; transform: rotate(90deg); } .wire small { display: none; } .wire > span { font-size: 13px; } .cloud { padding: 20px; min-height: 300px; } .cloud-heading > strong { font-size: 38px; } .idle-machine { margin: 16px 0; padding: 0; } .idle-machine svg { width: 64px; height: 50px; margin-bottom: 12px; } .idle-machine > span { max-width: none; font-size: 14px; } .cloud-footer { font-size: 12px; padding-top: 12px; } .lifecycle { margin: 12px 0 0; } .outcomes-zone { margin-top: 4px; } .inspector { padding: 24px; padding-top: 50px; bottom: 16px; right: 16px; } .inspector h2 { font-size: 21px; } }
</style>
